<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <RootNamespace>LegalAgent.Downloads</RootNamespace>
    <Version>1.0.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="LegalAgent.Downloads.Tests" />
  </ItemGroup>
</Project>
