<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <RootNamespace>LegalAgent.PdfParser</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="PdfPig" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="LegalAgent.PdfParser.Tests" />
  </ItemGroup>
</Project>
